# Generated by Django 4.1.7 on 2023-06-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('sem_num', models.IntegerField()),
                ('exp_file', models.FileField(max_length=250, upload_to='exptfiles/')),
            ],
        ),
    ]
