# Generated by Django 4.1.7 on 2023-06-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0002_contactus_alter_experiments_exp_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='fname',
            new_name='name',
        ),
    ]
